{% set name = "influxdb-client" %}
{% set version = "1.33.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/influxdb_client-{{ version }}.tar.gz
  sha256: 45f6a1763804a19b972890daf4c5f0bd2d3ae2f202b86451c579e09dcadd30e6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - certifi >=14.05.14
    - python >=3.6
    - python-dateutil >=2.5.3
    - rx >=3.0.1
    - setuptools >=21.0.0
    - six >=1.10
    - urllib3 >=1.15.1

test:
  imports:
    - influxdb_client
    - influxdb_client.client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/influxdata/influxdb-client-python
  summary: InfluxDB 2.0 Python client library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ruben-arts
