{% set name = "influxdb-client" %}
{% set version = "1.39.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/influxdb_client-{{ version }}.tar.gz
  sha256: 6a534913523bd262f1928e4ff80046bf95e313c1694ce13e45fd17eea90fe691

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - reactivex >=4.0.4
    - certifi >=14.05.14
    - python-dateutil >=2.5.3
    - setuptools >=21.0.0
    - urllib3 >=1.26.0

test:
  imports:
    - influxdb_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/influxdata/influxdb-client-python
  summary: InfluxDB 2.0 Python client library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - djhoese
    - ruben-arts
